.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH nanonoise 1 "February 25, 2009"
.\" Please update the above date whenever this man page is modified.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins (default)
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
nanonoise \- tool for Renoise to map MIDI messages to keystrokes
.SH SYNOPSIS
.B nanonoise
.RI [ options ] 
.SH DESCRIPTION
\fBnanonoise\fP is a quick hack to enable sending keystrokes to the
Renoise tracking software triggered by MIDI-CC messages and MIDI-MMC
commands. In this way you can send to Renoise commands via MIDI, which
are mapped to keyboard shortcuts.
.PP
.SH AUTHOR
This manual page was written by Jakob Flierl <jakob.flierl@gmail.com>,
for the Debian project (but may be used by others).
